"""Sprite Forge -- a local page for making units without a Claude session in the loop.

WHY THIS EXISTS
---------------
Making a new unit used to cost a conversation: /variants emitted create_character_state
kwargs for the agent to run over MCP, the agent fetched the rotations, ran
silhouette_report, published a static HTML sheet as an artifact, the owner said "keep 2, 5,
7" in chat, and a second skill packed and imported. Four handoffs, all through the agent,
and the owner's actual keep/cull call was never recorded anywhere a machine could read --
only judge's MEASUREMENT verdict (keep/flag/reject) landed in the manifest.

So this is the same pipeline with the agent made optional:

    prompt -> candidates -> measured contact sheet -> approve/deny -> atlas + Unreal

It owns none of the pipeline. Measurement is silhouette_report's, judging and the family
contract are variantpipe's, atlas rows are atlas.py's, packing is pixelpipe's, importing is
import_sprites.py's. What is new here is exactly three things: an HTTP surface, a REST
client for PixelLab (variantpipe deliberately has none -- see its header), and the
`variants.<slug>.owner` block, which is the first structured record of a human verdict in
this repo.

    py Scripts/art/forge.py --family pathfinder-line
    py Scripts/art/forge.py --family knight-melee-v2 --port 8770 --no-open
    py Scripts/art/forge.py --selftest

THE SLUG IS THE POINT
---------------------
The PixelLab account holds 158 characters, ~135 of them states named from truncated raw
prompts -- "Can you make a Turre", "Reshape this creatur" x5, "make one of stone". That
happened because create_character_state's `state_name` was never sent, so the service fell
back to the prompt. Forge requires a kebab-case slug and always sends it. It cannot fix the
135 already up there; it stops the 136th.

BOTH GENERATION PATHS, ONE CODE PATH
------------------------------------
`/` rescans RawArt/Renders/<family>/raw/ on every load. A variant generated here and one
generated by the agent over MCP and landed with `variantpipe.py fetch` are the same thing on
disk, so both appear with no sync step and no second reader.

PALETTE
-------
Full colour, no quantize -- docs/art/aesthetic-direction.md's 2026-07-28 amendment. Forge
never calls `pixelpipe.py quantize`, and atlas.py already defaults quantize:false.
`use_color_palette_from_reference` stays on because that is cohesion with the base
character, not the retired 4-value ramp.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import webbrowser
from pathlib import Path
from types import SimpleNamespace
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

sys.path.insert(0, str(Path(__file__).resolve().parent))
import silhouette_report as sr   # noqa: E402  (path insert must come first)
import variantpipe as vp         # noqa: E402
import roster as rs              # noqa: E402

REPO = vp.REPO
API = "https://api.pixellab.ai/v2"
UA = "Mozilla/5.0 (compatible; ELVTR-forge/1.0)"
Fail = vp.Fail

SLUG_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

# The two clauses every edit_description in this repo already ends with, hoisted out of the
# prose so they stop being retyped per variant. "Keep the head and legs clearly visible"
# is what stops a state collapsing into an unreadable mass at 56px; the palette clause plus
# the glow ban is aesthetic-direction.md's rule that light belongs to the flame alone.
# A family can override it with a "forge": {"tail": "..."} block in its family.json.
TAIL = ("Keep the head and legs clearly visible. Match the existing color palette exactly, "
        "no new colors, no glowing parts.")

# SKILL.md's measured range for a state on an 88-92px base. Shown before spending, never
# used as a gate -- the real number comes back as `usage` on the create response.
COST_LO, COST_HI = 20, 40


# ---------------------------------------------------------------- PixelLab REST
#
# variantpipe.py's header says PixelLab's generators are MCP tools and this project calls
# them through the agent. That is true of variantpipe and stays true. Forge is the local
# app the owner drives alone: it has no MCP client and no agent, so it talks to the v2 REST
# API the same service exposes. Endpoints and field names below are pinned against
# https://api.pixellab.ai/v2/openapi.json, not guessed.

def _find_bearer(obj):
    """The pixellab MCP server's Authorization header, wherever it is nested.

    ~/.claude.json keys mcpServers under each project path, so the block sits several
    levels down and its depth is not something to hardcode.
    """
    if isinstance(obj, dict):
        pl = obj.get("pixellab")
        if isinstance(pl, dict):
            auth = (pl.get("headers") or {}).get("Authorization", "")
            if auth.lower().startswith("bearer "):
                return auth[7:].strip()
        for v in obj.values():
            hit = _find_bearer(v)
            if hit:
                return hit
    elif isinstance(obj, list):
        for v in obj:
            hit = _find_bearer(v)
            if hit:
                return hit
    return None


def api_key():
    """Env first, then the MCP config. Never read from or written to the repo."""
    k = os.environ.get("PIXELLAB_API_KEY")
    if k:
        return k.strip()
    cfg = Path.home() / ".claude.json"
    if cfg.exists():
        try:
            k = _find_bearer(json.loads(cfg.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, UnicodeDecodeError):
            k = None
        if k:
            return k
    raise Fail("no PixelLab key: set PIXELLAB_API_KEY, or leave the pixellab MCP server "
               "configured in %s" % cfg)


def pl(method, path, body=None, timeout=90):
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = Request(API + path, data=data, method=method, headers={
        "Authorization": "Bearer " + api_key(),
        "Content-Type": "application/json",
        "User-Agent": UA,
    })
    try:
        with urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8") or "{}")
    except HTTPError as e:
        detail = e.read().decode("utf-8", "replace")[:400]
        raise Fail("PixelLab %s %s -> %s %s: %s" % (method, path, e.code, e.reason, detail))
    except URLError as e:
        raise Fail("PixelLab %s %s unreachable: %s" % (method, path, e.reason))


def balance():
    """(generations remaining, raw).

    `subscription.generations` is the REMAINING count, not the spent one -- measured
    2026-08-08 against get_balance's own "generations_remaining: 6083" while /balance
    returned {"generations": 6083.35, "total": 10000.0}. Read defensively anyway: the
    OpenAPI spec only $refs a Subscription schema, so the field names are not pinned by
    contract and a rename must dim the number, not break the page.
    """
    raw = pl("GET", "/balance", timeout=20)
    sub = raw.get("subscription") or {}
    for key in ("generations", "generations_remaining", "remaining"):
        if isinstance(sub.get(key), (int, float)):
            return int(sub[key]), raw
    return None, raw


# ---------------------------------------------------------------- prompt composition

def compose(edit, tail=TAIL):
    """The exact string sent as edit_description.

    Deterministic and from named parts, the same discipline as pixelpipe.compose_prompt --
    create_character_state takes no seed by default, so a recorded composition is the only
    thing that makes a state reproducible. Unlike pixelpipe's composer this appends NO
    palette clause and no house negatives: those exist to fight a 4-value ramp that was
    superseded 2026-07-28, and the base character's own palette is inherited through
    use_color_palette_from_reference instead.
    """
    edit = (edit or "").strip().rstrip(".").strip()
    if not edit:
        raise Fail("edit description is empty")
    tail = (tail or "").strip()
    return ("%s. %s" % (edit, tail)).strip() if tail else "%s." % edit


def check_slug(slug):
    if not SLUG_RE.match(slug or ""):
        raise Fail("'%s' is not a slug. Use kebab-case: lowercase letters, digits and "
                   "single hyphens (e.g. 'turret-nest'). This field is what stops the "
                   "account filling up with names like 'Can you make a Turre'." % slug)
    return slug


# ---------------------------------------------------------------- family + job state

def forge_block(family):
    """The optional "forge" block in family.json. Every field is optional; CLI flags win."""
    try:
        return (vp.load_spec(family).get("forge") or {})
    except Fail:
        return {}


def jobs_path(family):
    return vp.RENDERS / family / "forge-jobs.json"


def load_jobs(family):
    p = jobs_path(family)
    return vp.load_json(p) if p.exists() else {}


def save_jobs(family, jobs):
    # On disk, not just in memory: a state costs 20-40 generations and takes minutes, so
    # losing the character_id to a restart would strand spend with no way back to the art.
    vp.save_json(jobs_path(family), jobs)


def rotations_dir(family, slug):
    root = vp.raw_root(family)
    for name, d in sr.variant_dirs(root):
        if name == slug:
            return d
    raise Fail("no rotations on disk for '%s' under %s" % (slug, root))


def rotations_rel(family, slug):
    """Repo-relative rotations dir for a variant, in the form atlas.py --rotations wants."""
    return str(rotations_dir(family, slug).relative_to(REPO)).replace("\\", "/")


def slugify(s):
    s = re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")
    return s or "variant"


def character_id_of(family, slug):
    """The PixelLab character this variant IS -- the thing a refinement edits.

    Three places record it, in descending order of directness. The last two exist because
    most of what is on disk predates forge: pathfinder-line's twelve were an owner-supplied
    group download, and their ids live in the family's own naming map and in the group's
    source.json rather than in any job forge ran.
    """
    j = load_jobs(family).get(slug) or {}
    if j.get("character_id"):
        return j["character_id"]
    try:
        spec = vp.load_spec(family)
    except Fail:
        spec = {}
    for e in ((spec.get("naming") or {}).get("map") or []):
        if slug in (e.get("folder"), e.get("slug")) and e.get("state_id"):
            return e["state_id"]
    src = vp.RENDERS / family / "source.json"
    if src.exists():
        got = (vp.load_json(src).get("state_ids") or {}).get(slug)
        if got:
            return got
    raise Fail("no PixelLab character id recorded for '%s', so there is nothing to refine "
               "from. Its id is not in forge-jobs.json, family.json's naming.map, or "
               "source.json -- generate a fresh variant off the base instead." % slug)


def next_refine_slug(family, slug):
    """<slug>-r2, -r3, ... skipping anything already on disk or already queued."""
    stem = re.sub(r"-r\d+$", "", slugify(slug))
    taken = set(load_jobs(family))
    root = vp.raw_root(family)
    if root.exists():
        taken |= {n for n, _ in sr.variant_dirs(root)}
    n = 2
    while "%s-r%d" % (stem, n) in taken:
        n += 1
    return "%s-r%d" % (stem, n)


# ---------------------------------------------------------------- generate + poll

def start_state(family, base_id, slug, edit, tail=TAIL, seed=None, extra=None):
    check_slug(slug)
    jobs = load_jobs(family)
    if slug in jobs and jobs[slug].get("status") != "failed":
        raise Fail("'%s' already has a job (%s). Pick another slug."
                   % (slug, jobs[slug].get("status")))
    if slug in dict(sr.variant_dirs(vp.raw_root(family)) if vp.raw_root(family).exists() else []):
        raise Fail("'%s' already has renders on disk -- pick another slug" % slug)

    prompt = compose(edit, tail)
    body = {
        "character_id": base_id,
        "edit_description": prompt,
        "state_name": slug,                        # the whole point; see module docstring
        "use_color_palette_from_reference": True,  # cohesion with the base, not the ramp
    }
    if seed is not None:
        body["seed"] = int(seed)

    resp = pl("POST", "/create-character-state", body)
    jobs[slug] = {
        "slug": slug, "base_id": base_id,
        "character_id": resp["character_id"],
        "background_job_id": resp.get("background_job_id"),
        "edit": edit, "tail": tail, "prompt": prompt, "seed": seed,
        "usage": resp.get("usage"), "started": vp.now(), "status": "pending",
    }
    jobs[slug].update(extra or {})
    save_jobs(family, jobs)
    return jobs[slug]


# A refine is a correction, not a new idea, so its tail is the opposite of TAIL's: TAIL
# tells the model what to hold while it invents a variant, this tells it to invent nothing.
REFINE_TAIL = ("Change only what is described and nothing else. Keep the same character, "
               "pose, proportions and kit. Match the existing color palette exactly, no "
               "new colors, no glowing parts.")


def refine(family, slug, note, tail=REFINE_TAIL):
    """Generate a corrected candidate FROM this variant, not from the family base.

    A refinement's parent is the variant's own character, so the fix inherits everything
    already approved about it and only the named defect moves. Editing the base instead
    would throw away every earlier step.

    The note is logged on the PARENT's manifest entry whether or not the child ever lands.
    A defect worth describing is a finding about that sprite, and it survives the child
    being rejected.

    WHAT THIS CANNOT DO: fix a named rotation. A state edit re-renders the whole character,
    so "the shield drifts off to the side in north-east" moves nothing -- measured
    2026-08-08 on pavisewall, where the three rotations the note named came back
    byte-identical and the two that did change got worse (PIXELLAB-MCP.md). Refine changes
    what the subject IS. Per-facing geometry needs the anchor-and-rotate path.
    """
    note = (note or "").strip()
    if not note:
        raise Fail("say what needs cleaning up")
    parent = character_id_of(family, slug)
    child = next_refine_slug(family, slug)

    man = vp.load_manifest(family)
    man["family"] = family
    v = man.setdefault("variants", {}).setdefault(slug, {})
    v.setdefault("refine_notes", []).append(
        {"at": vp.now(), "note": note, "child": child})
    vp.save_json(vp.manifest_path(family), man)

    start_state(family, parent, child, note, tail,
                extra={"refined_from": slug, "refine_note": note})
    return {"queued": [child], "parent": slug, "parent_character_id": parent}


def rotation_strip(family, slug, scale=3):
    """All 8 rotations in one PNG, in sr.DIRECTIONS order.

    The card shows south, but the defects worth refining are usually the ones a south-only
    view cannot show -- a prop that survives facing the camera and vanishes from behind.
    silhouette_report says the same thing about judging; this is the same rule applied to
    describing a fix.
    """
    from PIL import Image
    d = rotations_dir(family, slug)
    ims = [Image.open(d / ("%s.png" % dirn)).convert("RGBA")
           for dirn in sr.DIRECTIONS if (d / ("%s.png" % dirn)).exists()]
    if not ims:
        raise Fail("no rotations on disk for '%s'" % slug)
    gap = 2
    w = sum(i.width for i in ims) * scale + gap * (len(ims) - 1)
    h = max(i.height for i in ims) * scale
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    x = 0
    for i in ims:
        r = i.resize((i.width * scale, i.height * scale), Image.NEAREST)
        out.alpha_composite(r, (x, h - r.height))
        x += r.width + gap
    buf = __import__("io").BytesIO()
    out.save(buf, "PNG")
    return buf.getvalue()


def turnaround(rot_dir, scale=2, ms=140):
    """The eight rotations as one looping animated WebP -- the unit turning on the spot.

    A still strip makes you compare eight things; a turnaround makes a break in the cycle
    jump out on its own, which is the whole problem with judging rear facings. Frames are
    padded to a common canvas and bottom-aligned so the figure does not bob: rotations are
    cropped to their own content and a naive paste would make the sprite hop every frame.
    Lossless, because these are flat-palette pixels and WebP's lossy mode invents colours
    at exactly the edges the silhouette is judged on.
    """
    from PIL import Image
    ims = [Image.open(rot_dir / ("%s.png" % d)).convert("RGBA")
           for d in sr.DIRECTIONS if (rot_dir / ("%s.png" % d)).exists()]
    if not ims:
        raise Fail("no rotations to animate in %s" % rot_dir)
    w = max(i.width for i in ims) * scale
    h = max(i.height for i in ims) * scale
    frames = []
    for i in ims:
        r = i.resize((i.width * scale, i.height * scale), Image.NEAREST)
        f = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        f.alpha_composite(r, ((w - r.width) // 2, h - r.height))
        frames.append(f)
    buf = __import__("io").BytesIO()
    frames[0].save(buf, "WEBP", save_all=True, append_images=frames[1:],
                   duration=ms, loop=0, lossless=True, minimize_size=True)
    return buf.getvalue()


def poll(family):
    """Advance every pending job. Returns the number that completed this pass.

    Polls GET /characters/{id} rather than the background job: the character carries both
    the terminal status AND rotation_urls, so one call answers "done?" and "where are the
    PNGs?" without depending on the job-status string enum, which the spec leaves open.
    """
    jobs = load_jobs(family)
    done = 0
    for slug, j in jobs.items():
        if j.get("status") != "pending":
            continue
        try:
            d = pl("GET", "/characters/%s" % j["character_id"], timeout=30)
        except Fail as e:
            j["last_error"] = str(e)
            continue
        j.pop("last_error", None)
        status = (d.get("status") or "").lower()
        rot = d.get("rotation_urls") or {}
        if status in ("failed", "error"):
            j["status"] = "failed"
            j["error"] = d.get("error") or status
            continue
        if status != "completed" or not rot:
            continue
        urls = [rot[k] for k in sr.DIRECTIONS if rot.get(k)]
        if len(urls) < len(sr.DIRECTIONS):
            # Judge rejects a variant missing rotations outright, so landing a partial set
            # would just manufacture a reject. Wait for the rest instead.
            continue
        # variantpipe owns downloading and the urls/fetched/files manifest entry; calling
        # its command keeps one implementation of the CDN's User-Agent and zip handling.
        vp.cmd_fetch(SimpleNamespace(family=family, variant=slug, url=urls))
        size = d.get("size") or {}
        j.update(status="done", fetched=vp.now(),
                 canvas=[size.get("width"), size.get("height")],
                 pixellab_name=d.get("name"), group_id=d.get("group_id"))
        done += 1
    save_jobs(family, jobs)
    return done


# ---------------------------------------------------------------- verdicts

def set_verdict(family, slug, verdict, note=""):
    """Write the owner's call into manifest.json under a key judge never touches.

    `verdict` there is variantpipe's MEASUREMENT verdict (keep/flag/reject) and gets
    overwritten every time judge runs. The human call goes in a sibling `owner` block so
    the two can disagree -- which is the useful case: a variant judge rejects as
    mechanically redundant can still be the one that reads best in a crowd.

    Approving also copies the generation record out of forge-jobs.json and into the same
    block, which is what makes the variant reproducible: create_character_state accepts no
    seed by default, so the composed prompt plus the base id IS the recipe.

    That record goes in the manifest and NOT into family.json's variants[], even though
    that array is the nominal home for a state's recipe. vp.save_json rewrites a whole file
    with json.dump, and family.json is hand-maintained with compact inline arrays -- so
    appending one variant reformats ~200 lines and buries the real change. The manifest is
    machine-written and already expanded, so it costs nothing there. `ship` prints the
    family.json line to paste if the owner wants `variantpipe.py plan` to replay it.
    """
    if verdict not in ("approve", "deny", "clear"):
        raise Fail("verdict must be approve, deny or clear (got %r)" % verdict)
    man = vp.load_manifest(family)
    man["family"] = family
    v = man.setdefault("variants", {}).setdefault(slug, {})
    if verdict == "clear":
        v.pop("owner", None)
    else:
        owner = v.setdefault("owner", {})
        owner.update(verdict=verdict, at=vp.now(), note=note or "")
        owner.setdefault("shipped", None)
        job = load_jobs(family).get(slug)
        if job and verdict == "approve":
            owner["generated"] = {
                "base_id": job.get("base_id"),
                "character_id": job.get("character_id"),
                "edit_description": job.get("prompt"),
                "seed": job.get("seed"),
                "tool": "forge.py create-character-state",
            }
    vp.save_json(vp.manifest_path(family), man)
    return v.get("owner")


def owner_of(man, slug):
    return ((man.get("variants") or {}).get(slug) or {}).get("owner") or {}


def spec_line(family, slug):
    """The family.json variants[] entry for an approved variant, as pasteable JSON.

    Printed rather than written, for the formatting reason in set_verdict's docstring.
    Paste it in and `variantpipe.py plan` can replay the state from the spec alone.
    """
    owner = owner_of(vp.load_manifest(family), slug)
    gen = owner.get("generated") or {}
    if not gen.get("edit_description"):
        return None
    return json.dumps({"slug": slug, "edit_description": gen["edit_description"],
                       "source": "generated"}, ensure_ascii=False)


# ---------------------------------------------------------------- ship

def run(cmd, cwd=REPO):
    p = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True)
    return {"cmd": " ".join(str(c) for c in cmd), "rc": p.returncode,
            "out": (p.stdout or "") + (p.stderr or "")}


def ue_import(request_id):
    """Import through the running editor, via the MCP driver Scripts/ue-mcp-call.py.

    Deliberately not a hand-rolled HTTP call: that script already speaks the meta-server's
    held-open-SSE protocol. If the editor is down this fails softly -- the sheet on disk is
    still correct and the import can be run later, so it must not fail the whole batch.
    """
    script = (REPO / "Scripts" / "art" / "import_sprites.py").as_posix()
    args = json.dumps({"Command": 'py "%s" %s' % (script, request_id)})
    r = run([sys.executable, str(REPO / "Scripts" / "ue-mcp-call.py"),
             "call", "Exec", args, "KindledConsoleToolset"])
    if r["rc"] != 0:
        r["out"] += ("\nEditor not reachable. The sheet is packed and correct; run this "
                     "in the editor when it is up:\n  py Scripts/art/import_sprites.py %s"
                     % request_id)
    return r


def ship(family, atlas, prefix):
    """Promote every approved-but-unshipped variant, once, as a batch.

    A batch and not an approve side-effect because an atlas row is not a pure data change:
    it needs a SwarmFragments.h constant bumped (a recompile) and the Niagara emitter's
    Sub UV widened. atlas.py prints both numbers and deliberately edits neither. Batching
    means one recompile per session instead of one per unit.
    """
    man = vp.load_manifest(family)
    todo = sorted(s for s, v in (man.get("variants") or {}).items()
                  if (v.get("owner") or {}).get("verdict") == "approve"
                  and not (v.get("owner") or {}).get("shipped"))
    if not todo:
        return {"shipped": [], "log": [], "note": "nothing approved and unshipped"}
    if not atlas or not prefix:
        raise Fail("ship needs an atlas request id and a prefix. Pass --atlas/--prefix, or "
                   'add "forge": {"atlas": "team-units", "prefix": "archer-"} to '
                   "docs/data/art/families/%s/family.json" % family)

    atlas_py = str(REPO / "Scripts" / "art" / "atlas.py")
    log, added = [], []
    for slug in todo:
        r = run([sys.executable, atlas_py, "add", atlas,
                 "--prefix", prefix + slug, "--rotations", rotations_rel(family, slug)])
        log.append(r)
        if r["rc"] == 0:
            added.append(slug)
    if added:
        log.append(run([sys.executable, str(REPO / "Scripts" / "art" / "pixelpipe.py"),
                        "pack", atlas]))
        log.append(ue_import(atlas))
    log.append(run([sys.executable, atlas_py, "check", "--all"]))

    man = vp.load_manifest(family)
    for slug in added:
        owner = man.setdefault("variants", {}).setdefault(slug, {}).setdefault("owner", {})
        owner["shipped"] = vp.now()
        owner["atlas_prefix"] = prefix + slug
    vp.save_json(vp.manifest_path(family), man)

    lines = [ln for ln in (spec_line(family, s) for s in added) if ln]
    if lines:
        log.append({"cmd": "(paste into docs/data/art/families/%s/family.json variants[] "
                           "so variantpipe.py plan can replay these)" % family,
                    "rc": 0, "out": ",\n".join(lines)})
    return {"shipped": added, "log": log}


# ---------------------------------------------------------------- measurement for cards

def nearest_sibling(bands, name, only=None):
    """(closest name, distance) on the three band midpoints.

    Variety is the question this page exists to answer, and the honest form of it is not
    "how far is this from the base" but "how close is this to whatever it most resembles" --
    a family fails when any two members collapse together, wherever they sit relative to
    the base. Distance is on band midpoints so a directional form is compared on its whole
    rotation range, not on its south frame (silhouette_report's own warning).
    """
    b = bands.get(name) or {}
    if b.get("missing"):
        return None, None
    def mid(x, k):
        return (x[k][0] + x[k][1]) / 2.0
    best, bestd = None, None
    for other, ob in bands.items():
        if other == name or ob.get("missing"):
            continue
        if only is not None and other not in only:
            continue
        d = sum(abs(mid(b, k) - mid(ob, k)) for k in ("aspect", "solidity", "asymmetry"))
        if bestd is None or d < bestd:
            best, bestd = other, d
    return best, bestd


def cards(family):
    """[(name, measure_dict)] with judge's verdict, the owner's verdict and the two
    nearest-neighbour numbers stamped on. judge_family is variantpipe's -- this adds the
    owner layer on top rather than re-deriving any measurement."""
    rows, verdicts, spec = vp.judge_family(family)
    bands = {n: verdicts[n]["band"] for n, _ in rows}
    man = vp.load_manifest(family)
    jobs = load_jobs(family)
    approved = {s for s, _ in rows if owner_of(man, s).get("verdict") == "approve"}

    out = []
    for name, m in sorted(rows, key=lambda kv: kv[0]):
        m["verdict"] = verdicts[name]["verdict"]
        m["reasons"] = verdicts[name]["reasons"]
        m["owner"] = owner_of(man, name)
        m["job"] = jobs.get(name)
        m["refine_notes"] = ((man.get("variants") or {}).get(name) or {}).get("refine_notes")
        m["near"], m["near_d"] = nearest_sibling(bands, name)
        m["near_ok"], m["near_ok_d"] = nearest_sibling(bands, name, only=approved - {name})
        m["band"] = bands.get(name) or {}
        out.append((name, m))
    return out, spec


# ---------------------------------------------------------------- page

PAGE_CSS = sr.SHEET_CSS + """
.cols{display:grid;gap:1.5rem;grid-template-columns:22rem minmax(0,1fr);align-items:start;}
@media (max-width:64rem){.cols{grid-template-columns:1fr;}}
.panel{background:var(--surface);border:1px solid var(--line);padding:1rem;display:flex;
  flex-direction:column;gap:.6rem;position:sticky;top:1rem;}
.panel label{font-family:var(--mono);font-size:.66rem;letter-spacing:.08em;
  text-transform:uppercase;color:var(--bone);display:block;margin-bottom:.2rem;}
.panel input,.panel textarea,.panel select{width:100%;box-sizing:border-box;
  background:var(--sunk);color:var(--ink);border:1px solid var(--line);padding:.4rem .5rem;
  font-family:var(--mono);font-size:.78rem;}
.panel textarea{min-height:7rem;resize:vertical;line-height:1.5;}
button{font-family:var(--mono);font-size:.7rem;text-transform:uppercase;letter-spacing:.06em;
  background:var(--sunk);color:var(--ink);border:1px solid var(--line);padding:.4rem .7rem;
  cursor:pointer;}
button:hover:not(:disabled){border-color:var(--bone);}
button:disabled{opacity:.4;cursor:default;}
button.go{background:var(--bone);color:var(--ground);border-color:var(--bone);}
button.no{border-color:var(--blood);color:var(--blood);}
.preview{background:var(--sunk);border:1px solid var(--line);padding:.5rem;
  font-family:var(--mono);font-size:.66rem;color:var(--dim);line-height:1.5;
  white-space:pre-wrap;word-break:break-word;max-height:9rem;overflow:auto;}
.grid{display:grid;gap:.75rem;grid-template-columns:repeat(auto-fill,minmax(12rem,1fr));}
.s.ok{border-color:var(--bone);}
.s.no{opacity:.45;}
.acts{display:flex;gap:.35rem;padding:.45rem .65rem;border-top:1px solid var(--line);}
.acts button{flex:1;padding:.3rem;}
.refine{border-top:1px solid var(--line);padding:.5rem .65rem;display:flex;
  flex-direction:column;gap:.4rem;}
/* The strip is 8 sprites wide, so it scrolls inside its OWN box -- the card stays a card
   and the page body never scrolls sideways. */
.rotwrap{overflow-x:auto;background:var(--sunk);border:1px solid var(--line);}
.refine .rot{max-width:none;height:auto;display:block;image-rendering:pixelated;}
.refine textarea{width:100%;box-sizing:border-box;min-height:4.5rem;background:var(--sunk);
  color:var(--ink);border:1px solid var(--line);padding:.4rem .5rem;font-family:var(--mono);
  font-size:.7rem;line-height:1.5;resize:vertical;}
.bar{display:flex;gap:.75rem;align-items:center;flex-wrap:wrap;font-family:var(--mono);
  font-size:.7rem;color:var(--dim);}
.err{color:var(--blood);font-family:var(--mono);font-size:.7rem;white-space:pre-wrap;}
pre.log{background:var(--sunk);border:1px solid var(--line);padding:.7rem;overflow:auto;
  font-size:.64rem;max-height:26rem;line-height:1.5;}
"""

PAGE_JS = """
async function post(path, body){
  const r = await fetch(path, {method:'POST', headers:{'Content-Type':'application/json'},
                              body: JSON.stringify(body||{})});
  const j = await r.json();
  if(!r.ok){ throw new Error(j.detail || j.error || r.statusText); }
  return j;
}
function say(msg, bad){
  const el = document.getElementById('msg');
  el.textContent = msg || ''; el.className = bad ? 'err' : 'bar';
}
function preview(){
  const edit = document.getElementById('edit').value.trim().replace(/\\.+$/,'');
  const tail = document.getElementById('tail').value.trim();
  const n = parseInt(document.getElementById('count').value || '1', 10);
  document.getElementById('prev').textContent = edit ? (edit + '. ' + tail) : '(empty)';
  document.getElementById('cost').textContent =
    n + ' x ~' + COST_LO + '-' + COST_HI + ' = ~' + (n*COST_LO) + '-' + (n*COST_HI) + ' generations';
}
async function generate(){
  const btn = document.getElementById('gen'); btn.disabled = true;
  try{
    const r = await post('/api/generate', {
      base_id: document.getElementById('base').value.trim(),
      slug: document.getElementById('slug').value.trim(),
      edit: document.getElementById('edit').value,
      tail: document.getElementById('tail').value,
      count: parseInt(document.getElementById('count').value||'1',10),
      seed: document.getElementById('seed').value.trim() || null});
    say('queued ' + r.queued.join(', ') + ' -- polling, ~2-4 min each');
    pump();
  }catch(e){ say(String(e.message), true); }
  btn.disabled = false;
}
async function verdict(slug, v){
  try{ await post('/api/verdict', {slug: slug, verdict: v}); location.reload(); }
  catch(e){ say(String(e.message), true); }
}
function toggleRefine(id){
  const box = document.getElementById('r-' + id);
  box.hidden = !box.hidden;
  if(!box.hidden){
    // 27 cards x 8 rotations is a lot of image requests to make on page load, so each
    // strip is fetched the first time its panel is opened and never again.
    const img = box.querySelector('img.rot');
    if(!img.src && img.dataset.src) img.src = img.dataset.src;
    box.querySelector('textarea').focus();
  }
}
async function sendRefine(slug, id){
  const note = document.getElementById('n-' + id).value.trim();
  if(!note){ say('say what needs cleaning up', true); return; }
  if(!confirm('Refine ' + slug + ' from itself, ~' + COST_LO + '-' + COST_HI +
              ' generations.\\n\\n' + note)) return;
  try{
    const r = await post('/api/refine', {slug: slug, note: note});
    say('queued ' + r.queued.join(', ') + ' from ' + r.parent + ' -- polling');
    toggleRefine(id);
    pump();
  }catch(e){ say(String(e.message), true); }
}
async function ship(){
  const btn = document.getElementById('shipbtn'); btn.disabled = true;
  say('shipping...');
  try{
    const r = await post('/api/ship', {});
    document.getElementById('log').textContent =
      (r.note ? r.note + '\\n\\n' : '') +
      r.log.map(x => '$ ' + x.cmd + '  (rc ' + x.rc + ')\\n' + x.out).join('\\n');
    say('shipped: ' + (r.shipped.join(', ') || 'nothing'));
  }catch(e){ say(String(e.message), true); }
  btn.disabled = false;
}
let pumping = false;
async function pump(){
  if(pumping) return; pumping = true;
  while(true){
    let j;
    try{ j = await (await fetch('/api/jobs')).json(); }
    catch(e){ break; }
    const pend = j.jobs.filter(x => x.status === 'pending');
    if(j.completed > 0){ location.reload(); return; }
    if(!pend.length) break;
    say(pend.length + ' generating: ' + pend.map(x=>x.slug).join(', '));
    await new Promise(r => setTimeout(r, 15000));
  }
  pumping = false;
}
window.addEventListener('DOMContentLoaded', () => {
  ['edit','tail','count'].forEach(id =>
    document.getElementById(id).addEventListener('input', preview));
  preview();
  if(HAS_PENDING) pump();
});
"""


def esc(s):
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def card_html(name, m, scale):
    o = m.get("owner") or {}
    ov = o.get("verdict")
    cls = "s ok" if ov == "approve" else ("s no" if ov == "deny" else "s")
    w = m["content"][0] * scale

    flags = []
    if m["verdict"] in ("reject", "flag"):
        flags.append('<em class="bad">judge: %s</em>' % m["verdict"])
    if not m["binary_alpha"]:
        flags.append('<em class="bad">soft alpha</em>')
    if o.get("shipped"):
        flags.append("<em>shipped</em>")

    band = m.get("band") or {}
    bandline = ("aspect band %.2f&ndash;%.2f across 8 rot"
                % (band["aspect"][0], band["aspect"][1])) if band.get("aspect") else \
               "incomplete rotations"
    near = ("nearest %s &Delta;%.2f" % (esc(m["near"]), m["near_d"])) \
        if m.get("near_d") is not None else "nearest &mdash;"
    if m.get("near_ok_d") is not None:
        near += " &middot; vs approved %s &Delta;%.2f" % (esc(m["near_ok"]), m["near_ok_d"])

    reasons = "".join('<p class="mx"><em class="bad">%s</em></p>' % esc(r)
                      for r in (m.get("reasons") or []))
    job = m.get("job") or {}
    if job.get("refined_from"):
        reasons += ('<p class="mx"><em>refined from %s: %s</em></p>'
                    % (esc(job["refined_from"]), esc(job.get("refine_note", ""))))
    for n in (m.get("refine_notes") or []):
        reasons += ('<p class="mx"><em class="bad">refine &rarr; %s: %s</em></p>'
                    % (esc(n.get("child", "?")), esc(n.get("note", ""))))

    return (
        '<figure class="%(cls)s" id="c-%(id)s">'
        '<div class="pair">'
        '<img src="data:image/png;base64,%(png)s" alt="%(nm)s" style="width:%(w)dpx">'
        '<img class="sil" src="data:image/png;base64,%(sil)s" alt="%(nm)s outline" style="width:%(w)dpx">'
        '</div>'
        '<figcaption><b>%(nm)s</b>'
        '<p class="mx">%(cw)d&times;%(ch)d &middot; aspect %(a).2f &middot; solidity %(s).2f'
        ' &middot; asym %(y).2f</p>'
        '<p class="mx">%(band)s</p>'
        '<p class="mx">%(near)s</p>'
        '%(flags)s%(reasons)s</figcaption>'
        '<div class="refine" id="r-%(id)s" hidden>'
        '<div class="rotwrap"><img class="rot" data-src="/rot/%(nm)s.png"'
        ' alt="8 rotations of %(nm)s"></div>'
        '<p class="mx">south &middot; south-east &middot; east &middot; north-east &middot; '
        'north &middot; north-west &middot; west &middot; south-west</p>'
        '<p class="mx"><em class="bad">Describe what the subject should BE, not how one '
        'facing looks.</em> A state edit re-renders the whole character; naming a rotation '
        'does not move it (measured &mdash; PIXELLAB-MCP.md). "Taller hood", "drop the '
        'arrows" work. "Fix the spear at north-east" does not.</p>'
        '<textarea id="n-%(id)s" placeholder="Give it a taller peaked hood and drop the '
        'arrows over the shoulder."></textarea>'
        '<div class="acts" style="border:0;padding:0">'
        '<button class="go" onclick="sendRefine(\'%(nm)s\',\'%(id)s\')">send refine</button>'
        '<button onclick="toggleRefine(\'%(id)s\')">cancel</button>'
        '</div></div>'
        '<div class="acts">'
        '<button class="%(okc)s" onclick="verdict(\'%(nm)s\',\'approve\')">approve</button>'
        '<button onclick="toggleRefine(\'%(id)s\')">refine</button>'
        '<button class="%(noc)s" onclick="verdict(\'%(nm)s\',\'%(nv)s\')">%(nl)s</button>'
        '</div></figure>'
        % {"cls": cls, "id": slugify(name), "nm": esc(name), "w": w,
           "png": sr.b64(m["crop"]), "sil": sr.b64(sr.flat(m["crop"])),
           "cw": m["content"][0], "ch": m["content"][1], "a": m["aspect"],
           "s": m["solidity"], "y": m["asymmetry"], "band": bandline, "near": near,
           "flags": ('<p class="mx">%s</p>' % " ".join(flags)) if flags else "",
           "reasons": reasons,
           "okc": "go" if ov == "approve" else "",
           "noc": "no" if ov != "deny" else "",
           "nv": "clear" if ov else "deny", "nl": "undo" if ov else "deny"})


def page(family, atlas, prefix, scale):
    try:
        rows, spec = cards(family)
    except Fail as e:
        rows, spec = [], {}
        first_error = str(e)
    else:
        first_error = ""

    fb = forge_block(family)
    base = (spec or {}).get("base") or {}
    tail = fb.get("tail", TAIL)
    jobs = load_jobs(family)
    pending = [j for j in jobs.values() if j.get("status") == "pending"]
    man = vp.load_manifest(family)
    ready = [n for n, _ in rows
             if owner_of(man, n).get("verdict") == "approve"
             and not owner_of(man, n).get("shipped")]

    try:
        gens, _ = balance()
        bal = "%s generations left" % (gens if gens is not None else "?")
    except Fail as e:
        bal = "balance unavailable (%s)" % e

    canvas = base.get("canvas_size")
    basenote = ("base %s &middot; canvas %s px (a state inherits it &mdash; `size` is not "
                "the canvas)" % (esc(base.get("character_id") or "?"), canvas or "?"))

    return """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sprite Forge &middot; %(family)s</title>
<style>%(css)s</style></head><body>
<div class="wrap">
  <header>
    <p class="eyebrow"><a href="/" style="color:var(--bone)">&larr; roster</a>
      &middot; sprite forge</p>
    <h1>%(family)s</h1>
    <p>%(basenote)s. Front-facing render and its flat outline; every number is measured
    across all eight rotations, never from the south frame alone.</p>
  </header>
  <p id="msg" class="bar">%(err)s</p>
  <div class="cols">
    <form class="panel" onsubmit="event.preventDefault();generate()">
      <div><label for="base">base character id</label>
        <input id="base" value="%(base_id)s"></div>
      <div><label for="slug">slug (kebab-case, becomes state_name)</label>
        <input id="slug" placeholder="turret-nest"></div>
      <div><label for="edit">what changes</label>
        <textarea id="edit" placeholder="A shinobi: body tightly wrapped and narrow head to foot, twin sword hilts crossed in an X above the shoulders."></textarea></div>
      <div><label for="tail">constant clauses (every variant)</label>
        <textarea id="tail" style="min-height:4.5rem">%(tail)s</textarea></div>
      <div style="display:flex;gap:.5rem">
        <div style="flex:1"><label for="count">re-rolls</label>
          <input id="count" type="number" min="1" max="8" value="1"></div>
        <div style="flex:1"><label for="seed">seed (optional)</label>
          <input id="seed" placeholder="none"></div>
      </div>
      <div><label>composed prompt</label><div id="prev" class="preview"></div></div>
      <p class="bar"><span id="cost"></span> &middot; %(bal)s</p>
      <button id="gen" class="go" type="submit">generate</button>
      <hr style="border:0;border-top:1px solid var(--line);margin:.3rem 0">
      <p class="bar">%(nready)d approved and unshipped%(shiptarget)s</p>
      <button id="shipbtn" type="button" onclick="ship()" %(shipdis)s>ship approved</button>
    </form>
    <section>
      <div class="grid">
%(cards)s
      </div>
      <pre class="log" id="log"></pre>
    </section>
  </div>
</div>
<script>const COST_LO=%(lo)d, COST_HI=%(hi)d, HAS_PENDING=%(pending)s;%(js)s</script>
</body></html>""" % {
        "family": esc(family), "css": PAGE_CSS, "js": PAGE_JS,
        "basenote": basenote,
        "err": esc(first_error),
        "base_id": esc(base.get("character_id") or ""),
        "tail": esc(tail), "bal": esc(bal),
        "lo": COST_LO, "hi": COST_HI,
        "pending": "true" if pending else "false",
        "nready": len(ready),
        "shiptarget": (" &rarr; %s (%s&lt;slug&gt;)" % (esc(atlas), esc(prefix)))
                      if atlas and prefix else " &mdash; no atlas configured",
        "shipdis": "" if (ready and atlas and prefix) else "disabled",
        "cards": "\n".join(card_html(n, m, scale) for n, m in rows)
                 or '<p class="bar">no renders on disk yet</p>',
    }


# ---------------------------------------------------------------- roster page

ROSTER_CSS = PAGE_CSS + """
.grp{margin:0 0 1.6rem;}
.grp>h2{font-size:1.15rem;margin:0 0 .5rem;font-weight:600;display:flex;gap:.6rem;
  align-items:baseline;}
.grp>h2 span{font-family:var(--mono);font-size:.7rem;color:var(--dim);font-weight:400;}
.row{display:grid;grid-template-columns:4.5rem minmax(9rem,1fr) 6.2rem 4.2rem 8rem 4.5rem;
  gap:.6rem;align-items:center;background:var(--surface);border:1px solid var(--line);
  border-bottom:0;padding:.35rem .6rem;}
.grp .row:last-of-type{border-bottom:1px solid var(--line);}
@media (max-width:60rem){.row{grid-template-columns:4.5rem 1fr;row-gap:.3rem;}}
.row img{height:3.4rem;width:auto;max-width:4.5rem;object-fit:contain;object-position:bottom;
  image-rendering:pixelated;background:var(--sunk);}
.row b{font-size:.9rem;font-weight:600;overflow-wrap:anywhere;}
.row .sub{font-family:var(--mono);font-size:.6rem;color:var(--dim);}
.chip{font-family:var(--mono);font-size:.6rem;letter-spacing:.06em;text-transform:uppercase;
  border:1px solid var(--line);padding:.1rem .35rem;display:inline-block;color:var(--dim);}
.chip.on{border-color:var(--bone);color:var(--bone);}
.chip.live{background:var(--bone);color:var(--ground);border-color:var(--bone);}
.chip.bad{border-color:var(--blood);color:var(--blood);}
.row select{background:var(--sunk);color:var(--ink);border:1px solid var(--line);
  font-family:var(--mono);font-size:.65rem;padding:.2rem;max-width:100%;}
.det{grid-column:1/-1;border-top:1px solid var(--line);padding:.6rem 0 .2rem;display:flex;
  flex-direction:column;gap:.5rem;}
.det textarea{width:100%;box-sizing:border-box;min-height:3.5rem;background:var(--sunk);
  color:var(--ink);border:1px solid var(--line);padding:.4rem .5rem;font-family:var(--mono);
  font-size:.7rem;line-height:1.5;resize:vertical;}
.note{font-family:var(--mono);font-size:.66rem;color:var(--dim);border-left:2px solid var(--line);
  padding-left:.5rem;line-height:1.55;}
.note b{color:var(--bone);font-weight:400;}
.cap{display:flex;gap:.4rem;align-items:center;font-family:var(--mono);font-size:.66rem;}
.cap i{display:block;height:.5rem;background:var(--bone);}
.cap u{display:block;height:.5rem;background:var(--line);text-decoration:none;}
.capbar{display:flex;width:7rem;border:1px solid var(--line);}
nav{display:flex;gap:.5rem;flex-wrap:wrap;font-family:var(--mono);font-size:.7rem;}
nav a{color:var(--bone);text-decoration:none;border:1px solid var(--line);padding:.2rem .5rem;}
nav a:hover{border-color:var(--bone);}
"""

ROSTER_JS = """
async function rpost(path, body){
  const r = await fetch(path, {method:'POST', headers:{'Content-Type':'application/json'},
                              body: JSON.stringify(body)});
  const j = await r.json();
  if(!r.ok) throw new Error(j.detail || r.statusText);
  return j;
}
function flash(el, ok){
  el.style.borderColor = ok ? 'var(--bone)' : 'var(--blood)';
  setTimeout(() => { el.style.borderColor = ''; }, 900);
}
async function setField(key, field, el){
  try{ await rpost('/api/roster/field', {key:key, field:field, value:el.value}); flash(el, true); }
  catch(e){ flash(el, false); alert(e.message); }
}
async function addNote(key, id){
  const ta = document.getElementById('nt-' + id);
  if(!ta.value.trim()) return;
  try{
    const j = await rpost('/api/roster/note', {key:key, text:ta.value});
    const list = document.getElementById('nl-' + id);
    const n = j.notes[j.notes.length-1];
    const p = document.createElement('p'); p.className = 'note';
    p.innerHTML = '<b>' + n.at.slice(0,16).replace('T',' ') + '</b> ' +
                  n.text.replace(/[<>&]/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]));
    list.appendChild(p); ta.value = '';
  }catch(e){ alert(e.message); }
}
function toggleDet(id){
  const d = document.getElementById('d-' + id);
  d.hidden = !d.hidden;
  if(!d.hidden){
    // Animated WebPs are only fetched for rows you actually open -- 135 looping
    // turnarounds decoding at once is not something a page should ever ask for.
    d.querySelectorAll('img[data-src]').forEach(i => { i.src = i.dataset.src; i.removeAttribute('data-src'); });
  }
}
async function addConcept(){
  const g = document.getElementById('c-group').value;
  const slug = document.getElementById('c-slug').value.trim();
  const title = document.getElementById('c-title').value.trim();
  const exp = document.getElementById('c-exp').value.trim();
  if(!slug){ alert('a concept unit needs a slug'); return; }
  try{ await rpost('/api/roster/concept', {slug:slug, title:title, group:g, expectation:exp});
       location.reload(); }
  catch(e){ alert(e.message); }
}
window.addEventListener('DOMContentLoaded', () => {
  // The first thumbnail of every row is a still south frame; only opened rows animate.
  document.querySelectorAll('img.thumb[data-src]').forEach(i => {
    i.src = i.dataset.src; i.removeAttribute('data-src');
  });
});
"""

STAGE_HELP = {
    "concept": "named and wanted, no art yet",
    "generated": "eight rotations on disk",
    "measured": "silhouette measured, judge verdict recorded",
    "approved": "you approved it",
    "animated": "walk, attack and death frames exist",
    "packed": "atlas row, packed sheet, imported texture",
    "live": "the C++ constant and the sheet agree - it is on screen",
}


def unit_id(key):
    return re.sub(r"[^a-z0-9]+", "-", key.lower()).strip("-")


def roster_row(u, groups):
    uid = unit_id(u["key"])
    rot = u.get("rotations")
    stage_cls = "chip live" if u["stage"] == "live" else (
        "chip on" if u["stage"] in ("approved", "animated", "packed") else "chip")
    if u["rejected"]:
        stage_cls = "chip bad"

    anim = " ".join(
        '<span class="chip%s" title="%s">%s</span>'
        % (" on" if u["anim"].get(s) else "", s, s[0].upper())
        for s in rs.ANIM_STATES)

    thumb = ('<img class="thumb" data-src="/still?key=%s" alt="%s">' % (esc(u["key"]), esc(u["title"]))
             ) if rot else '<span class="chip">no art</span>'

    where = []
    if u.get("family"):
        where.append('<a href="/family/%s">%s</a>' % (esc(u["family"]), esc(u["family"])))
    if u.get("request"):
        where.append(esc(u["request"]))
    if u.get("packed"):
        where.append("%s #%s" % (esc(u["packed"][0]),
                                 "-" if u["packed"][2] is None else u["packed"][2]))
    if u.get("unregistered"):
        where.append("<em>no family.json</em>")
    if not u["gate_passed"] and u["stage"] != "concept":
        where.append("<em>never gated</em>")

    opts = "".join('<option%s>%s</option>'
                   % (" selected" if g == u["group"] else "", esc(g)) for g in groups)

    notes = "".join('<p class="note"><b>%s</b> %s</p>'
                    % (esc(n.get("at", "")[:16].replace("T", " ")), esc(n.get("text", "")))
                    for n in u["notes"])
    for n in (u.get("refine_notes") or []):
        notes += ('<p class="note"><b>refine &rarr; %s</b> %s</p>'
                  % (esc(n.get("child", "")), esc(n.get("note", ""))))

    turn = ('<img data-src="/turn?key=%s" alt="%s turnaround" '
            'style="height:8rem;width:auto;image-rendering:pixelated;background:var(--sunk)">'
            % (esc(u["key"]), esc(u["title"]))) if rot else ""

    return (
        '<div class="row">'
        '%(thumb)s'
        '<div><b>%(title)s</b><div class="sub">%(where)s</div></div>'
        '<span class="%(sc)s" title="%(help)s">%(stage)s</span>'
        '<div>%(anim)s</div>'
        '<select onchange="setField(\'%(key)s\',\'group\',this)">%(opts)s</select>'
        '<button onclick="toggleDet(\'%(uid)s\')">%(nn)s</button>'
        '<div class="det" id="d-%(uid)s" hidden>'
        '%(turn)s'
        '<div><label class="sub">what this unit is for</label>'
        '<textarea onchange="setField(\'%(key)s\',\'expectation\',this)" '
        'placeholder="What job does this unit do, and how should it read at a glance?"'
        '>%(exp)s</textarea></div>'
        '<div id="nl-%(uid)s">%(notes)s</div>'
        '<div><textarea id="nt-%(uid)s" style="min-height:2.6rem" '
        'placeholder="Add a note..."></textarea>'
        '<button onclick="addNote(\'%(key)s\',\'%(uid)s\')">add note</button></div>'
        '</div></div>'
        % {"thumb": thumb, "title": esc(u["title"]), "where": " &middot; ".join(where),
           "sc": stage_cls, "stage": esc(u["stage"]),
           "help": esc(STAGE_HELP.get(u["stage"], "")),
           "anim": anim, "opts": opts, "key": esc(u["key"]), "uid": uid,
           "exp": esc(u["expectation"]), "notes": notes, "turn": turn,
           "nn": ("%d note%s" % (len(u["notes"]), "" if len(u["notes"]) == 1 else "s"))
                 if u["notes"] else "open"})


def roster_page():
    units, r, ctx = rs.build()
    summary = rs.summary(units, ctx)
    groups = r.get("groups") or list(rs.DEFAULT_GROUPS)

    caps = []
    for block, (used, cap) in sorted(summary["capacity"].items()):
        pct = int(round(100.0 * used / cap))
        caps.append('<div class="cap"><span>%s %d/%d</span><span class="capbar">'
                    '<i style="width:%d%%"></i><u style="width:%d%%"></u></span></div>'
                    % (esc(block), used, cap, pct, 100 - pct))

    drift = []
    for rid, (n, declared) in sorted(summary["atlas"].items()):
        ok = n == declared
        drift.append('<span class="chip%s">%s %d/%d</span>'
                     % ("" if ok else " bad", esc(rid), n, declared))

    stages = " ".join('<span class="chip%s">%d %s</span>'
                      % (" on" if k == "live" else "", v, k)
                      for k, v in summary["stages"].items() if v)

    active = [u for u in units if not u["rejected"]]
    rejected = [u for u in units if u["rejected"]]

    sections = []
    for g in groups:
        us = [u for u in active if u["group"] == g]
        if not us:
            continue
        live = sum(1 for u in us if u["stage"] == "live")
        sections.append('<section class="grp"><h2>%s <span>%d units &middot; %d live</span></h2>%s</section>'
                        % (esc(g), len(us), live,
                           "".join(roster_row(u, groups) for u in us)))
    if rejected:
        sections.append('<section class="grp"><h2>rejected <span>%d &middot; nothing was '
                        'moved or deleted</span></h2>%s</section>'
                        % (len(rejected), "".join(roster_row(u, groups) for u in rejected)))

    fams = sorted({u["family"] for u in units if u.get("family")})
    nav = '<a href="/official">&#9733; official</a> <a href="/selects">&#10003; selects</a> ' + \
          " ".join('<a href="/family/%s">%s</a>' % (esc(f), esc(f)) for f in fams)

    return """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Kindled &middot; unit roster</title><style>%(css)s</style></head><body>
<div class="wrap">
  <header>
    <p class="eyebrow">Kindled &middot; roster</p>
    <h1>Every unit the game has or wants</h1>
    <p>Stage is computed from what is on disk and in the manifests, never stored, so it
    cannot go stale. Only the group, the expectation and the notes are yours to set.
    Open a row for the turnaround.</p>
  </header>
  <div class="bar">%(stages)s</div>
  <div class="bar">%(caps)s %(drift)s</div>
  <details><summary class="bar" style="cursor:pointer">add a unit that does not exist yet</summary>
    <div class="panel" style="position:static;margin-top:.6rem;max-width:34rem">
      <div style="display:flex;gap:.5rem">
        <div style="flex:1"><label for="c-slug">slug</label><input id="c-slug" placeholder="lampbearer"></div>
        <div style="flex:1"><label for="c-title">title</label><input id="c-title" placeholder="Lampbearer"></div>
        <div style="flex:1"><label for="c-group">group</label>
          <select id="c-group" style="width:100%%">%(gopts)s</select></div>
      </div>
      <div><label for="c-exp">what it is for</label>
        <textarea id="c-exp" style="min-height:3.5rem"></textarea></div>
      <button class="go" onclick="addConcept()">add to roster</button>
    </div>
  </details>
  <nav>%(nav)s</nav>
%(sections)s
</div>
<script>%(js)s</script></body></html>""" % {
        "css": ROSTER_CSS, "js": ROSTER_JS, "stages": stages,
        "caps": "".join(caps), "drift": " ".join(drift),
        "gopts": "".join("<option>%s</option>" % esc(g) for g in groups),
        "nav": nav, "sections": "\n".join(sections),
    }


# ---------------------------------------------------------------- selects page
#
# The owner's approve/deny over every generated look, cross-family. Approve copies the
# rotations into RawArt/Aaron Selects/<Branch>/<slug>/rotations -- the folder the owner already
# keeps by hand for Aseprite + the PixelLab plugin -- so "official" is literally "on disk in
# Selects". Deny never deletes: a hand-kept dir may hold Aseprite edits, so it is moved to
# Selects/_denied/<slug> and RawArt/Renders is never touched (retention rule).

SELECTS = REPO / "RawArt" / "Aaron Selects"
SELECTS_JSON = "selects.json"


def selects_json():
    return SELECTS / SELECTS_JSON


def rel(p):
    p = Path(p)
    try:
        return str(p.relative_to(REPO)).replace("\\", "/")
    except ValueError:
        return str(p).replace("\\", "/")


def selects_load():
    return vp.load_json(selects_json()) if selects_json().exists() else {}


def selects_branches():
    if not SELECTS.exists():
        return []
    return sorted(p.name for p in SELECTS.iterdir() if p.is_dir() and not p.name.startswith("_"))


def selects_candidates():
    """(family, slug, dir) for every rotations dir with a south frame under RENDERS/*/raw."""
    out = []
    if not vp.RENDERS.exists():
        return out
    for fam in sorted(p.name for p in vp.RENDERS.iterdir() if (p / "raw").is_dir()):
        for name, d in sr.variant_dirs(vp.raw_root(fam)):
            if (Path(d) / "south.png").exists():
                out.append((fam, name, Path(d)))
    return out


def selects_seed(rec, cands):
    """A hand-made <Branch>/<slug> dir counts as approved -- the folder predates the record."""
    by_slug = {}
    for fam, slug, d in cands:
        by_slug.setdefault(slug, (fam, d))
    changed = False
    for b in selects_branches():
        for p in (SELECTS / b).iterdir():
            if not p.is_dir() or p.name not in by_slug:
                continue
            fam, d = by_slug[p.name]
            key = "%s/%s" % (fam, p.name)
            if key not in rec:
                rec[key] = {"branch": b, "verdict": "approve", "at": vp.now(),
                            "source": rel(d),
                            "seeded": True}
                changed = True
    if changed:
        vp.save_json(selects_json(), rec)
    return rec


def select_dir(slug):
    """Where the slug currently sits in Selects, if anywhere."""
    for b in selects_branches():
        if (SELECTS / b / slug).is_dir():
            return SELECTS / b / slug
    return None


def set_select(key, verdict, branch=""):
    if verdict not in ("approve", "deny", "clear"):
        raise Fail("verdict must be approve, deny or clear (got %r)" % verdict)
    fam, _, slug = (key or "").partition("/")
    if not slug:
        raise Fail("bad key %r" % key)
    rec = selects_load()
    old = select_dir(slug)
    if old is not None:
        import shutil
        parked = SELECTS / "_denied" / slug
        if parked.exists():
            shutil.rmtree(parked)
        parked.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(old), str(parked))
    if verdict == "approve":
        import shutil
        branch = (branch or "").strip().strip("/\\")
        if not branch or branch.startswith("_"):
            raise Fail("approve needs a branch name (not starting with _)")
        src = unit_rotations(key)
        shutil.copytree(src, SELECTS / branch / slug / "rotations")
        rec[key] = {"branch": branch, "verdict": "approve", "at": vp.now(),
                    "source": rel(src)}
    elif verdict == "deny":
        rec[key] = {"branch": (rec.get(key) or {}).get("branch"), "verdict": "deny", "at": vp.now()}
    else:
        rec.pop(key, None)
    vp.save_json(selects_json(), rec)
    # mirror approve/deny into the family manifest when there is one; clear only forgets
    # the selects record so it cannot wipe a verdict forge itself wrote earlier
    if verdict != "clear" and vp.spec_path(fam).exists():
        set_verdict(fam, slug, verdict)
    return rec.get(key)


SELECTS_CSS = ROSTER_CSS + """
.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(11rem,1fr));gap:.6rem;}
.card{background:var(--surface);border:1px solid var(--line);padding:.5rem;display:flex;
  flex-direction:column;gap:.35rem;}
.card.ok{border-color:var(--bone);} .card.no{opacity:.45;}
.card img{height:6rem;width:100%;object-fit:contain;object-position:bottom;
  image-rendering:pixelated;background:var(--sunk);}
.card b{font-size:.78rem;overflow-wrap:anywhere;}
.card .btns{display:flex;gap:.3rem;flex-wrap:wrap;}
.card button{background:var(--sunk);color:var(--ink);border:1px solid var(--line);
  font-family:var(--mono);font-size:.62rem;padding:.2rem .45rem;cursor:pointer;}
.card button:hover{border-color:var(--bone);}
.card a{color:var(--bone);font-family:var(--mono);font-size:.6rem;}
summary{cursor:pointer;} details.grp{margin-bottom:1rem;} details.grp>summary h2{display:inline-flex;}
#branch{background:var(--sunk);color:var(--ink);border:1px solid var(--line);
  font-family:var(--mono);font-size:.7rem;padding:.25rem;}
body.hide-denied .card.no{display:none;}
"""

SELECTS_JS = ROSTER_JS + """
function branchOf(){
  const s = document.getElementById('branch');
  return s.value === '__new' ? (document.getElementById('branch-new').value || '') : s.value;
}
async function sel(key, verdict, btn){
  const card = btn.closest('.card');
  try{
    await rpost('/api/select', {key:key, verdict:verdict, branch:branchOf()});
    location.reload();
  }catch(e){ flash(card, false); alert(e.message); }
}
function toggleDenied(cb){ document.body.classList.toggle('hide-denied', !cb.checked); }
document.addEventListener('DOMContentLoaded', () => {
  const s = document.getElementById('branch');
  s.addEventListener('change', () => {
    document.getElementById('branch-new').style.display = s.value === '__new' ? '' : 'none'; });
});
"""


def selects_page():
    cands = selects_candidates()
    rec = selects_seed(selects_load(), cands)
    fams = {}
    for fam, slug, d in cands:
        fams.setdefault(fam, []).append((slug, d))

    sections = []
    tot = {"approve": 0, "deny": 0, "pending": 0}
    for fam in sorted(fams):
        cards, n = [], {"approve": 0, "deny": 0, "pending": 0}
        for slug, d in fams[fam]:
            key = "%s/%s" % (fam, slug)
            r = rec.get(key) or {}
            v = r.get("verdict") or "pending"
            n[v] += 1
            cls = {"approve": " ok", "deny": " no"}.get(v, "")
            where = ('<a href="/api/open?key=%s" target="_blank">%s/%s &#8599;</a>'
                     % (esc(key), esc(r.get("branch") or ""), esc(slug))) if v == "approve" else \
                    ('<span class="sub">%s</span>' % esc(v))
            cards.append(
                '<div class="card%s"><img src="/still?key=%s" alt="" loading="lazy" '
                'onmouseenter="this.src=\'/turn?key=%s\'" onmouseleave="this.src=\'/still?key=%s\'">'
                '<b>%s</b>%s<div class="btns">'
                '<button onclick="sel(\'%s\',\'approve\',this)">approve</button>'
                '<button onclick="sel(\'%s\',\'deny\',this)">deny</button>'
                '<button onclick="sel(\'%s\',\'clear\',this)">clear</button></div></div>'
                % (cls, esc(key), esc(key), esc(key), esc(slug), where,
                   esc(key), esc(key), esc(key)))
        for k in tot:
            tot[k] += n[k]
        sections.append(
            '<details class="grp"%s><summary><h2>%s <span>%d looks &middot; %d approved '
            '&middot; %d denied &middot; %d pending</span></h2></summary><div class="cards">%s'
            '</div></details>'
            % (" open" if n["pending"] or n["approve"] else "", esc(fam), len(fams[fam]),
               n["approve"], n["deny"], n["pending"], "".join(cards)))

    bopts = "".join('<option>%s</option>' % esc(b) for b in selects_branches())
    return """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Kindled &middot; selects</title><style>%(css)s</style></head><body class="hide-denied">
<div class="wrap">
  <header>
    <p class="eyebrow"><a href="/" style="color:var(--bone)">&larr; roster</a> &middot; selects</p>
    <h1>Which looks are official</h1>
    <p>Every generated look, by family. <b>Approve</b> copies its rotations into
    <code>RawArt/Aaron Selects/&lt;branch&gt;/&lt;slug&gt;/</code> for Aseprite;
    <b>deny</b> parks any Selects copy under <code>_denied/</code> and never touches Renders.
    Hand-made Selects folders were read as approved.</p>
  </header>
  <div class="bar">
    <span class="chip on">%(a)d approved</span> <span class="chip">%(d)d denied</span>
    <span class="chip">%(p)d pending</span>
    &nbsp; approve into <select id="branch">%(bopts)s<option value="__new">new branch&hellip;</option></select>
    <input id="branch-new" placeholder="Branch name" style="display:none">
    &nbsp; <label><input type="checkbox" onchange="toggleDenied(this)"> show denied</label>
  </div>
%(sections)s
</div>
<script>%(js)s</script></body></html>""" % {
        "css": SELECTS_CSS, "js": SELECTS_JS, "bopts": bopts,
        "a": tot["approve"], "d": tot["deny"], "p": tot["pending"],
        "sections": "\n".join(sections)}


def official_page():
    """The official set: approved selects only, grouped by branch, thumbnails from the Selects
    copy (so Aseprite edits show), deny to demote. Nothing else -- the owner asked for
    approve/deny and no more; generation and editing live elsewhere."""
    rec = selects_seed(selects_load(), selects_candidates())
    branches = {}
    for key, r in rec.items():
        if r.get("verdict") == "approve":
            branches.setdefault(r.get("branch") or "?", []).append(key)
    sections = []
    for b in sorted(branches):
        cards = []
        for key in sorted(branches[b]):
            slug = key.partition("/")[2]
            cards.append(
                '<div class="card ok"><img src="/still?key=%s&sel=1" alt="" loading="lazy" '
                "onmouseenter=\"this.src='/turn?key=%s&sel=1'\" "
                "onmouseleave=\"this.src='/still?key=%s&sel=1'\">"
                '<b>%s</b><a href="/api/open?key=%s" target="_blank">%s &#8599;</a>'
                "<div class=\"btns\"><button onclick=\"sel('%s','deny',this)\">deny</button>"
                '</div></div>'
                % (esc(key), esc(key), esc(key), esc(slug), esc(key), esc(key), esc(key)))
        sections.append(
            '<section class="grp"><h2>%s <span>%d official</span></h2><div class="cards">%s'
            '</div></section>' % (esc(b), len(cards), "".join(cards)))
    n = sum(len(v) for v in branches.values())
    return """<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Kindled &middot; official characters</title><style>%(css)s</style></head><body>
<div class="wrap">
  <header>
    <p class="eyebrow"><a href="/" style="color:var(--bone)">&larr; roster</a> &middot;
    <a href="/selects" style="color:var(--bone)">selects</a> &middot; official</p>
    <h1>Official characters</h1>
    <p>What is on disk in <code>RawArt/Aaron Selects/&lt;branch&gt;/</code>, by branch --
    the frames shown are the Selects copies, so Aseprite edits appear here. <b>Deny</b> parks
    the folder under <code>_denied/</code>. To add one, approve it on the selects page.</p>
  </header>
  <div class="bar"><span class="chip on">%(n)d official</span>
    <select id="branch" style="display:none"><option></option></select>
    <input id="branch-new" style="display:none"></div>
%(sections)s
</div>
<script>%(js)s</script></body></html>""" % {
        "css": SELECTS_CSS, "js": SELECTS_JS, "n": n,
        "sections": "\n".join(sections) or "<p>Nothing approved yet.</p>"}


def unit_rotations(key):
    """The rotations dir for a roster key.

    Resolved from the key's own shape rather than by searching a built roster: every
    thumbnail and turnaround on the page calls this, and rs.build() walks every family,
    every request and both atlases. One image request must not cost a full inventory.
    """
    kind, _, rest = (key or "").partition("/")
    if not rest:
        raise Fail("bad roster key %r" % key)

    if kind == "shipped":
        d = (vp.RENDERS / rest).resolve()
    elif kind == "request":
        req_path = rs.REQUESTS / ("%s.json" % rest)
        if not req_path.exists():
            raise Fail("no request '%s'" % rest)
        req = vp.load_json(req_path)
        rev = vp.RENDERS / rest / ("r%d" % req.get("revision", 1))
        d = next((c for c in (rev / "raw" / "rotation", rev / "quantized" / "rotation")
                  if (c / "south.png").exists()), None)
    elif kind == "concept":
        raise Fail("'%s' has no art yet" % key)
    else:                                   # "<family>/<slug>"
        root = vp.raw_root(kind)
        d = dict(sr.variant_dirs(root)).get(rest) if root.exists() else None

    if d is None or not (Path(d) / "south.png").exists():
        raise Fail("no rotations on disk for '%s'" % key)
    return Path(d)


def still(rot_dir, scale=2):
    """The south frame alone, for the roster's row thumbnail."""
    from PIL import Image
    im = Image.open(rot_dir / "south.png").convert("RGBA")
    im = im.resize((im.width * scale, im.height * scale), Image.NEAREST)
    buf = __import__("io").BytesIO()
    im.save(buf, "WEBP", lossless=True)
    return buf.getvalue()


# ---------------------------------------------------------------- app

def build_app(family, atlas, prefix, scale):
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import HTMLResponse, JSONResponse, Response

    app = FastAPI(title="Sprite Forge")

    def guard(fn, *a, **kw):
        try:
            return fn(*a, **kw)
        except Fail as e:
            raise HTTPException(status_code=400, detail=str(e))

    @app.get("/", response_class=HTMLResponse)
    def index():
        return roster_page()

    @app.get("/family/{fam}", response_class=HTMLResponse)
    def family_view(fam: str):
        # A family's own forge block is authoritative; the CLI flags only stand in for the
        # family the server was started on, so browsing to another one cannot ship it into
        # the wrong atlas by inheriting the wrong prefix.
        fb = forge_block(fam)
        return page(fam,
                    fb.get("atlas") or (atlas if fam == family else None),
                    fb.get("prefix") or (prefix if fam == family else None), scale)

    @app.get("/selects", response_class=HTMLResponse)
    def selects_view():
        return selects_page()

    @app.get("/official", response_class=HTMLResponse)
    def official_view():
        return official_page()

    @app.post("/api/select")
    def api_select(body: dict):
        return {"select": guard(set_select, body.get("key"), body.get("verdict"),
                                body.get("branch", ""))}

    @app.get("/api/open")
    def api_open(key: str):
        d = select_dir((key or "").partition("/")[2])
        if d is None:
            raise HTTPException(status_code=404, detail="not in Selects")
        os.startfile(str(d))
        return {"opened": str(d)}

    def rot_for(key, sel):
        d = select_dir((key or "").partition("/")[2]) if sel else None
        return d / "rotations" if d and (d / "rotations" / "south.png").exists() else unit_rotations(key)

    @app.get("/still")
    def api_still(key: str, sel: int = 0):
        png = guard(lambda: still(rot_for(key, sel), max(1, scale - 1)))
        return Response(png, media_type="image/webp",
                        headers={"Cache-Control": "no-store"})

    @app.get("/turn")
    def api_turn(key: str, sel: int = 0):
        webp = guard(lambda: turnaround(rot_for(key, sel), max(1, scale - 1)))
        return Response(webp, media_type="image/webp",
                        headers={"Cache-Control": "no-store"})

    @app.post("/api/roster/field")
    def api_field(body: dict):
        return {"unit": guard(rs.set_field, body.get("key"), body.get("field"),
                              body.get("value"), body.get("title"))}

    @app.post("/api/roster/note")
    def api_note(body: dict):
        return {"notes": guard(rs.add_note, body.get("key"), body.get("text"))}

    @app.post("/api/roster/concept")
    def api_concept(body: dict):
        return {"key": guard(rs.add_concept, body.get("slug"), body.get("title"),
                             body.get("group"), body.get("expectation"))}

    @app.post("/api/generate")
    def api_generate(body: dict):
        slug = check_slug((body.get("slug") or "").strip())
        base_id = (body.get("base_id") or "").strip()
        if not base_id:
            raise HTTPException(400, "no base character id")
        count = max(1, min(8, int(body.get("count") or 1)))
        seed = body.get("seed")
        seed = int(seed) if str(seed or "").strip().lstrip("-").isdigit() else None
        tail = body.get("tail", TAIL)
        # Re-rolls of one description get -a/-b/-c, so the slug still names the folder and
        # the state, and two candidates for the same idea never collide.
        slugs = [slug] if count == 1 else \
            ["%s-%s" % (slug, chr(ord("a") + i)) for i in range(count)]
        queued = []
        for i, s in enumerate(slugs):
            guard(start_state, family, base_id, s, body.get("edit"), tail,
                  None if seed is None else seed + i)
            queued.append(s)
        return {"queued": queued}

    @app.get("/api/jobs")
    def api_jobs():
        completed = guard(poll, family)
        return {"completed": completed, "jobs": list(load_jobs(family).values())}

    @app.get("/rot/{slug}.png")
    def api_rot(slug: str):
        png = guard(rotation_strip, family, slug, scale)
        return Response(png, media_type="image/png",
                        headers={"Cache-Control": "no-store"})

    @app.post("/api/refine")
    def api_refine(body: dict):
        return guard(refine, family, (body.get("slug") or "").strip(), body.get("note"))

    @app.post("/api/verdict")
    def api_verdict(body: dict):
        return {"owner": guard(set_verdict, family, body.get("slug"),
                               body.get("verdict"), body.get("note", ""))}

    @app.post("/api/ship")
    def api_ship(body: dict = None):
        return JSONResponse(guard(ship, family, atlas, prefix))

    return app


# ---------------------------------------------------------------- selftest

def selftest():
    import tempfile
    # composition is deterministic and adds no palette clause
    a = compose("A shinobi, narrow and wrapped.")
    assert a == compose("A shinobi, narrow and wrapped"), a
    assert a.endswith(TAIL), a
    assert "palette exactly" in a and "#" not in a, a
    assert compose("x", tail="") == "x."

    # the slug rule is the whole fix for the account's 135 prompt-named states
    for good in ("turret-nest", "v2", "hazmat-bulk-3"):
        assert check_slug(good) == good
    for bad in ("Can you make a Turre", "Turret_Nest", "", "trailing-", "UPPER"):
        try:
            check_slug(bad)
            raise AssertionError("accepted bad slug %r" % bad)
        except Fail:
            pass

    # verdict round-trips without touching judge's own verdict key, carries the recipe,
    # and never rewrites family.json (whose compact hand-authored arrays a json.dump
    # would explode into a ~200-line diff around one real change)
    with tempfile.TemporaryDirectory() as td:
        fam = "forge-selftest"
        real_fam, real_ren = vp.FAMILIES, vp.RENDERS
        try:
            vp.FAMILIES, vp.RENDERS = Path(td) / "fam", Path(td) / "ren"
            spec = {"family": fam, "axis": {"name": "aspect", "description": "d"},
                    "constant": "c", "variants": [{"slug": "old"}]}
            vp.save_json(vp.spec_path(fam), spec)
            before = vp.spec_path(fam).read_text(encoding="utf-8")
            vp.save_json(vp.manifest_path(fam), {
                "family": fam,
                "variants": {"a": {"verdict": "reject", "reasons": ["r"], "measured": {}}}})
            save_jobs(fam, {"a": {"slug": "a", "base_id": "B", "character_id": "C",
                                  "prompt": "a shinobi. " + TAIL, "seed": None,
                                  "status": "done"}})

            set_verdict(fam, "a", "approve", "reads best in a crowd")
            m = vp.load_manifest(fam)
            assert m["variants"]["a"]["verdict"] == "reject"          # judge's, untouched
            assert m["variants"]["a"]["owner"]["verdict"] == "approve"
            assert m["variants"]["a"]["owner"]["shipped"] is None
            assert m["variants"]["a"]["owner"]["generated"]["base_id"] == "B"
            assert vp.spec_path(fam).read_text(encoding="utf-8") == before, \
                "approve must not rewrite family.json"
            assert '"slug": "a"' in spec_line(fam, "a")

            # deny records a verdict and no recipe, and moves nothing on disk
            set_verdict(fam, "a", "deny")
            assert "generated" in vp.load_manifest(fam)["variants"]["a"]["owner"]
            set_verdict(fam, "a", "clear")
            assert "owner" not in vp.load_manifest(fam)["variants"]["a"]
            assert spec_line(fam, "a") is None
        finally:
            vp.FAMILIES, vp.RENDERS = real_fam, real_ren

    # a refine names its parent, survives a legacy name, and never collides
    with tempfile.TemporaryDirectory() as td:
        fam = "forge-refine"
        real_fam, real_ren = vp.FAMILIES, vp.RENDERS
        try:
            vp.FAMILIES, vp.RENDERS = Path(td) / "fam", Path(td) / "ren"
            assert slugify("Can_you_make_a_Turre") == "can-you-make-a-turre"
            assert slugify("!!!") == "variant"
            # the three id sources, in priority order
            vp.save_json(vp.spec_path(fam), {
                "family": fam, "axis": {"name": "a", "description": "d"}, "constant": "c",
                "variants": [{"slug": "x"}],
                "naming": {"map": [{"folder": "Legacy_Name", "state_id": "FROM-MAP"}]}})
            vp.save_json(vp.RENDERS / fam / "source.json",
                         {"state_ids": {"Other_One": "FROM-SOURCE"}})
            save_jobs(fam, {"forged": {"slug": "forged", "character_id": "FROM-JOB",
                                       "status": "done"}})
            assert character_id_of(fam, "forged") == "FROM-JOB"
            assert character_id_of(fam, "Legacy_Name") == "FROM-MAP"
            assert character_id_of(fam, "Other_One") == "FROM-SOURCE"
            try:
                character_id_of(fam, "nobody")
                raise AssertionError("refined a variant with no recorded id")
            except Fail:
                pass
            # -r2 first, and a refine of a refine keeps counting on the same stem
            assert next_refine_slug(fam, "Legacy_Name") == "legacy-name-r2"
            save_jobs(fam, {**load_jobs(fam), "forged-r2": {"slug": "forged-r2"}})
            assert next_refine_slug(fam, "forged") == "forged-r3"
            assert next_refine_slug(fam, "forged-r2") == "forged-r3"
            assert check_slug(next_refine_slug(fam, "Can_you_make_a_Turre"))
        finally:
            vp.FAMILIES, vp.RENDERS = real_fam, real_ren

    # selects: a hand-made dir seeds as approved, approve copies, deny parks (never deletes),
    # clear forgets, and Renders is never written
    with tempfile.TemporaryDirectory() as td:
        global SELECTS
        real_fam, real_ren, real_sel = vp.FAMILIES, vp.RENDERS, SELECTS
        try:
            vp.FAMILIES, vp.RENDERS, SELECTS = Path(td) / "fam", Path(td) / "ren", Path(td) / "sel"
            def rot(fam, slug):
                d = vp.RENDERS / fam / "raw" / slug / "rotations"
                d.mkdir(parents=True)
                for n in ("south", "north"):
                    (d / ("%s.png" % n)).write_bytes(b"png")
                return d
            rot("famA", "look1"); rot("famA", "look2")
            hand = SELECTS / "Human Soldier Branch" / "look2" / "rotations"
            hand.mkdir(parents=True); (hand / "south.png").write_bytes(b"png")
            (hand.parent / "edit.aseprite").write_bytes(b"ase")

            rec = selects_seed(selects_load(), selects_candidates())
            assert rec["famA/look2"]["verdict"] == "approve" and rec["famA/look2"]["seeded"]
            assert rec["famA/look2"]["branch"] == "Human Soldier Branch"

            set_select("famA/look1", "approve", "Elf Branch")
            assert (SELECTS / "Elf Branch" / "look1" / "rotations" / "north.png").exists()
            assert selects_load()["famA/look1"]["branch"] == "Elf Branch"
            try:
                set_select("famA/look1", "approve", "")
                raise AssertionError("approved with no branch")
            except Fail:
                pass

            set_select("famA/look2", "deny")
            assert not (SELECTS / "Human Soldier Branch" / "look2").exists()
            assert (SELECTS / "_denied" / "look2" / "edit.aseprite").exists(), "deny must not delete"
            assert selects_load()["famA/look2"]["verdict"] == "deny"
            assert (vp.RENDERS / "famA" / "raw" / "look2" / "rotations" / "south.png").exists()
            assert "_denied" not in selects_branches()
            html = official_page()
            assert "look1" in html and "look2" not in html, "official page must list approved only"

            set_select("famA/look1", "clear")
            assert "famA/look1" not in selects_load()
            assert not (SELECTS / "Elf Branch" / "look1").exists()
            assert not (vp.FAMILIES / "famA").exists(), "no manifest for a family with no spec"
        finally:
            vp.FAMILIES, vp.RENDERS, SELECTS = real_fam, real_ren, real_sel

    # nearest-neighbour is on band midpoints, and a variant with no band is not compared
    bands = {"x": {"aspect": [1.0, 1.0], "solidity": [.5, .5], "asymmetry": [.1, .1]},
             "y": {"aspect": [1.1, 1.1], "solidity": [.5, .5], "asymmetry": [.1, .1]},
             "z": {"aspect": [3.0, 3.0], "solidity": [.9, .9], "asymmetry": [.4, .4]},
             "w": {"missing": 3}}
    n, d = nearest_sibling(bands, "x")
    assert n == "y" and abs(d - 0.1) < 1e-9, (n, d)
    assert nearest_sibling(bands, "x", only={"z"})[0] == "z"
    assert nearest_sibling(bands, "w") == (None, None)

    print("forge selftest OK")
    return 0


# ---------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--family", default="pathfinder-line")
    ap.add_argument("--atlas", default=None, help="composite request id to ship into")
    ap.add_argument("--prefix", default=None, help="atlas prefix, e.g. archer-")
    ap.add_argument("--port", type=int, default=8770)
    ap.add_argument("--scale", type=int, default=3)
    ap.add_argument("--no-open", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    fb = forge_block(args.family)
    atlas = args.atlas or fb.get("atlas")
    prefix = args.prefix or fb.get("prefix")

    import uvicorn
    url = "http://127.0.0.1:%d/" % args.port
    print("forge  family=%s  atlas=%s  prefix=%s\n%s"
          % (args.family, atlas or "-", prefix or "-", url))
    if not args.no_open:
        webbrowser.open(url)
    uvicorn.run(build_app(args.family, atlas, prefix, args.scale),
                host="127.0.0.1", port=args.port, log_level="warning")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Fail as e:
        print("FAIL  %s" % e, file=sys.stderr)
        sys.exit(1)
