#!/usr/bin/env python3
"""backlog_guard.py — PreToolUse hook protecting the backlog's approval gate.

Wired in .claude/settings.json for Edit|Write|MultiEdit|Bash|PowerShell. Reads the
hook payload on stdin and enforces two things.

DENY, on file writes:

  1. Any task-*.md edit that sets status to approved / done / rejected / parked.
     Those are the owner's verdicts, and they are simply not reachable by editing
     a file. They go through `py Scripts/backlog.py <verb>`.
  2. Hand-edits to INDEX.md, which is generated by `backlog.py reindex`.
  3. Hand-edits to LOG.md, which is append-only via backlog.py.

ASK, on shell commands:

  4. Any invocation of backlog.py with a privileged verb. This is the human gate,
     and it has to be enforced here rather than by omission from an allowlist:
     .claude/settings.local.json already carries a blanket `Bash(py *)` allow rule,
     so relying on "we never allowlisted it" would leave the gate wide open. A hook
     `ask` decision overrides an allow rule, which a narrower allow rule would not.

Everything else passes silently: agents can create `proposed` tasks, move their own
work to in-progress / needs-review, and run every read-only backlog command without
friction.

This is a speed bump plus an audit trail, not a cryptographic gate. Its job is to
make approval impossible to perform incidentally — the prompt raised by rule 4 is
where a human actually decides.
"""

from __future__ import annotations

import json
import re
import sys

PRIVILEGED = re.compile(r"(?m)^\s*status:\s*[\"']?(approved|done|rejected|parked)\b")
TASK_FILE = re.compile(r"docs/backlog/task-\d+[^/]*\.md$", re.IGNORECASE)
# backlog.py invoked with a verb only the owner may authorise. Deliberately loose
# about the interpreter and path form — `py Scripts\backlog.py`, `python3
# C:/.../backlog.py` and `& backlog.py` must all be caught.
PRIVILEGED_CMD = re.compile(
    r"backlog\.py[\"']?\s+(approve|done|reject|park)\b", re.IGNORECASE)


def decide(decision: str, reason: str) -> None:
    json.dump({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": decision,
            "permissionDecisionReason": reason,
        }
    }, sys.stdout)
    sys.stdout.flush()
    sys.exit(0)


def deny(reason: str) -> None:
    decide("deny", reason)


def incoming_text(tool_name: str, ti: dict) -> str:
    """Every chunk of text this call would write into the file."""
    parts = [ti.get("content") or "", ti.get("new_string") or ""]
    for e in ti.get("edits") or []:
        if isinstance(e, dict):
            parts.append(e.get("new_string") or "")
    return "\n".join(parts)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0  # never block on a payload we cannot read

    tool = payload.get("tool_name", "")
    ti = payload.get("tool_input") or {}

    if tool in {"Bash", "PowerShell"}:
        cmd = str(ti.get("command") or "")
        m = PRIVILEGED_CMD.search(cmd)
        if m:
            decide("ask",
                   f"This records the owner's '{m.group(1)}' verdict on a backlog task "
                   f"and writes it to docs/backlog/LOG.md. Approve only if the owner "
                   f"asked for it — an agent must never authorise its own work.")
        return 0

    if tool not in {"Edit", "Write", "MultiEdit", "NotebookEdit"}:
        return 0

    path = str(ti.get("file_path") or ti.get("notebook_path") or "").replace("\\", "/")
    if "docs/backlog/" not in path.lower():
        return 0

    lower = path.lower()
    if lower.endswith("docs/backlog/index.md"):
        deny("docs/backlog/INDEX.md is generated. Edit the task-*.md files, then run "
             "`py Scripts/backlog.py reindex`.")
    if lower.endswith("docs/backlog/log.md"):
        deny("docs/backlog/LOG.md is append-only and written by Scripts/backlog.py. "
             "Do not hand-edit it.")

    if not TASK_FILE.search(path):
        return 0

    m = PRIVILEGED.search(incoming_text(tool, ti))
    if m:
        status = m.group(1)
        verb = {"approved": "approve", "rejected": "reject",
                "parked": "park", "done": "done"}[status]
        deny(
            f"Blocked: this edit sets status to '{status}', which is the owner's verdict "
            f"to give. Approving, rejecting, parking, and closing a task go through "
            f"`py Scripts/backlog.py {verb} <id>`, which prompts the owner and records "
            f"the decision in docs/backlog/LOG.md. "
            f"Agents may set: proposed, in-progress, needs-review."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
